base/agent/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import DataRequired, FileAllowed
from wtforms import FileField, TextAreaField, PasswordField, BooleanField
from wtforms.fields import SubmitField, StringField, DateField, IntegerField, RadioField, SelectField
from wtforms.fields.html5 import URLField
from wtforms.validators import EqualTo, ValidationError, Email, Length


from base.models import Agent



class RegForm(FlaskForm):
    agent_first_name = StringField(validators=[DataRequired()])
    agent_last_name = StringField(validators=[DataRequired()])
    country = SelectField()


    agent_password = PasswordField(validators=[DataRequired()])
    confirm_password = PasswordField('Confirm password',
                                     validators=[DataRequired(), EqualTo('password', message='Passwords must match')])

    agent_email = StringField(validators=[DataRequired()])
    agent_phone_no = StringField(validators=[DataRequired()])
    gender = SelectField(choices=[('male', "Male"), ("female", "Female")],
                         validators=[DataRequired()])
    agent_photo = FileField('Upload', validators=[FileAllowed(['jpg', 'png']), DataRequired()])
    submit = SubmitField('Register')


class LoginForm(FlaskForm):
    agent_email = StringField(validators=[DataRequired()])
    agent_password = PasswordField(validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Sign In')




class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        agent = Agent.query.filter_by(email=email.data).first()
        if agent is None:
            raise ValidationError('There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')


class ChangePasswordForm(FlaskForm):
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=8, max=255)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

base/agent/routes.py
import os


from flask import *
from flask_login import current_user, login_user, login_required, logout_user

from base import db, bcrypt
from base.agent.email import send_email
from base.agent.forms import RegForm, LoginForm, RequestResetForm, ResetPasswordForm
from base.agent.token import generate_confirmation_token, confirm_token
from base.agent.util import send_reset_email
from base.home.utils import save_img
from base.models import Agent, Apartment, AgentSchema

agent = Blueprint('agent', __name__)





@agent.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    agent= Agent.query.filter_by(email=email).first_or_404()
    if agent.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        agent.confirmed = True
        db.session.add(agent)
        db.session.commit()
        flash('Your account has been confirmed. Thanks!', 'success')
    return redirect(url_for('main.home'))

@agent.route('/agents')
def agents():
    page = request.args.get('page', 1, type=int)
    agent = Agent.query.paginate(page=page, per_page=100)

    return render_template('agents.html', agent=agent)


@agent.route('/search/agent', methods=['POST'])
def agent_search():
    data = request.form.get('text')
    agent = Agent.query.filter_by(first_name=data).all()
    if not agent:
        agent = Agent.query.filter_by(last_name=data).all()
        if not agent:
            agent = Agent.query.filter_by(email=data).all()
    agent_schema = AgentSchema(many=True)
    res = agent_schema.dump(agent)
    return jsonify(res)


@agent.route('/profile/<string:agent_name>/<string:agent_last_name>')
def profile(agent_name, agent_last_name):
    page = request.args.get('page', 1, type=int)
    agent = Agent.query.filter_by(first_name=agent_name).filter_by(last_name=agent_last_name).first()
    apartment = Apartment.query.filter_by(agent=agent.id).order_by(Apartment.date_uploaded.desc()).paginate(page=page,
                                                                                                            per_page=10)
    return render_template('profile.html', agent=agent, apartment=apartment)

@agent.route('/agent/<string:agent_name>/<string:agent_last_name>')
@login_required
def agent_apt(agent_name, agent_last_name):

    page = request.args.get('page', 1, type=int)
    agent = Agent.query.filter_by(first_name=agent_name).filter_by(last_name=agent_last_name).first()
    if agent.first_name is not current_user.first_name:
        abort(403)
    apartment = Apartment.query.filter_by(broker=current_user).order_by(Apartment.date_uploaded.desc()).paginate(page=page,
                                                                                                            per_page=10)
    return render_template('current_agent.html', agent=agent, apartment=apartment)



@agent.route('/agent/<string:agent_name>/<string:agent_last_name>/delete/<string:apartment_public_id>')
def delete_agent_apt(agent_name, agent_last_name, apartment_public_id):
    apartment = Apartment.query.filter_by(broker=current_user).filter_by(public_id=apartment_public_id).first()
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file0}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file2}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file3}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file4}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file5}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file6}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file7}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file8}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.image_file9}")
    os.remove(f"{os.path.abspath('base/static/Apartment_pics')}/{apartment.video_tour}")

    db.session.delete(apartment)
    db.session.commit()
    return redirect(url_for('agent.agent_apt', agent_name= current_user.first_name, agent_last_name=current_user.last_name))


@agent.route('/register', methods=['GET', 'POST'])
def register():
    form = RegForm()
    if form.is_submitted():
        photo_file4 = save_img(form.agent_photo.data)
        file4 = request.files['agent_photo']
        hashed_password = bcrypt.generate_password_hash(form.agent_password.data).decode('utf-8')
        agent = Agent()
        agent.first_name = form.agent_first_name.data
        agent.last_name = form.agent_last_name.data
        agent.password = hashed_password
        agent.country = form.country.data
        agent.email = form.agent_email.data
        agent.gender = form.gender.data
        agent.phone_no = form.agent_phone_no.data
        agent.agent_image_file = photo_file4
        agent.agent_photo_data = file4.read()
        agent.confirmed = False
        db.session.add(agent)
        db.session.commit()
        token = generate_confirmation_token(agent.email)
        confirm_url = url_for('agent.confirm_email', token=token, _external=True)
        html = render_template('confirm_url.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(agent.email, subject, html)

        login_user(agent)

        flash('A confirmation email has been sent via email.', 'success')
        # flash('Your account has been created! Log in', 'success')

        return redirect(url_for("agent.unconfirmed"))

    return render_template('register.html', form=form, title="Register")



@agent.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        agent =Agent.query.filter_by(email=form.email.data).first()
        send_reset_email(agent)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('agent.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@agent.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    agent= Agent.verify_reset_token(token)
    if agent is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('agent.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        agent.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('agent.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)



@agent.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect(url_for('main.home'))
    return render_template('unconfirmed.html', title='Unconfirmed')


@agent.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('agent.confirm_email', token=token, _external=True)
    html = render_template('confirm_url.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('agent.unconfirmed'))


@agent.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = Agent.query.filter_by(email=form.agent_email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.agent_password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login failed. please check email and password', 'danger')
        if current_user.is_authenticated:
            return redirect(url_for('main.home'))

    return render_template('login.html', title="Login", form=form)


@agent.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

base/templates/agents.html
{%extends 'layout.html'%}
{% block content%}


    <!-- Offcanvas Menu Wrapper Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <span class="icon_close"></span>
        </div>
        <div class="logo">
           <a  href="{{ url_for('main.home') }}">

                 <h2>Souia</h2>
            </a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="om-widget">

               <a class="hw-btn"  href="{{ url_for('main.property_submit') }}">Submit property</a>
        </div>

    </div>
    <!-- Offcanvas Menu Wrapper End -->



    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section spad set-bg" data-setbg="{{  url_for('static', filename= 'img/breadcrumb-bg.jpg') }}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h4>Owners/Agents</h4>
                        <div class="bt-option">
                            <a  href="{{ url_for('main.home') }}"><i class="fa fa-home"></i> Home</a>
                            <span>Agents</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Agent Section Begin -->
    <section class="agent-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="agent-search-form">
                        <form action="#">
                            <input type="text" id="livebox" placeholder="Find agent by Name or Email address">
                                  </form>
                         <span id="datalist" ></span>
                        <script src="{{ url_for('static', filename='ajax.js') }}"></script>
<script src="{{ url_for('static', filename='agent_search.js') }}">

</script>
                    </div>
                </div>
            </div>
            <div class="as-slider owl-carousel">
                     {%for agt in agent.items%}
                <div class="row">

                    <div class="col-lg-4 col-md-6">

                        <div class="as-item">
                            <div class="as-pic">

                                <img src="{{  url_for('static', filename= 'Apartment_pics/' + agt.agent_image_file) }}">

                            </div>
                            <div class="as-text">
                                <div class="at-title">
                                    <h6>{{agt.first_name}} {{agt.last_name}}</h6>

                                </div>
                                <ul>
                                    <li>Property <span>{{agt.total}}</span></li>
                                    <li>Email <span>{{agt.email}}</span></li>
                                    <li>Phone <span>{{agt.phone_no}}</span></li>
                                </ul>
                                <a  href="{{ url_for('agent.profile', agent_name=agt.first_name, agent_last_name=agt.last_name) }}">View profile</a>
                            </div>
                        </div>

                    </div>

                </div>
                {% endfor %}

{% if agent.has_prev %}
         <div class="col-lg-12">
                    <div class="loadmore-btn">
        <a class="btn btn-outline-info" href="{{ url_for('agent.agents', page=agent.prev_num) }}"> Newer </a>{% else %}

            </div>
        </div>
                {% endif %}
{% if agent.has_next %}
         <div class="col-lg-12">
                    <div class="loadmore-btn">
        <a class="btn btn-outline-info" href="{{ url_for('agent.agents',   page=agent.next_num) }}"> Older </a>{% else %}

            </div>
        </div>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- Agent Section End -->

  {%endblock content%}

base/templates/current_agent.html
{%extends 'layout.html'%}
{% block content%}

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Wrapper Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <span class="icon_close"></span>
        </div>
        <div class="logo">
            <a  href="{{ url_for('main.home') }}">


                <h2>Souia</h2>
            </a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="om-widget">

              <a class="hw-btn"  href="{{ url_for('main.property_submit') }}">Submit property</a>
        </div>

    </div>
    <!-- Offcanvas Menu Wrapper End -->



    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section spad set-bg" data-setbg="{{  url_for('static', filename= 'img/breadcrumb-bg.jpg') }}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h4>Profile</h4>
                        <div class="bt-option">
                            <a  href="{{ url_for('main.home') }}">

               <i class="fa fa-home"></i> Home</a>
                             <a  href="{{ url_for('agent.agents') }}">Agents</a>
                            <span>{{current_user.first_name}} {{current_user.last_name}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Profile Section Begin -->
    <section class="profile-section spad">
        <div class="container">
            <div class="profile-agent-content">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="profile-agent-info">
                            <div class="pi-pic">

                                <img src="{{  url_for('static', filename= 'Apartment_pics/' + agent.agent_image_file) }}">

                            </div>
                            <div class="pi-text">
                                <h5>{{agent.first_name}} {{agent.last_name}}</h5>
                                <span>From {{agent.country}}</span>
                                <p><span>Since</span> {{agent.date_registered.strftime('%B %Y ')}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="profile-agent-widget">
                            <ul>
                                <li>Properties <span>{{apartment.total}}</span></li>
                                <li>Email <span>{{agent.email}}</span></li>
                                <li>Phone <span>{{agent.phone_no}}</span></li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- Profile Section End -->

    <!-- Property Section Begin -->
    <section class="property-section profile-page spad">
        <div class="container">
            <div class="row">
                {%for apt in apartment.items%}
                <div class="col-lg-4">

                    <div class="property-item">
                        <div class="pi-pic set-bg" data-setbg="{{  url_for('static', filename= 'Apartment_pics/' + apt.image_file) }}">
                            <div class="label">{{apt.property_status}}</div>
                        </div>
                         <div class="pd-title">
                             <a href="{{ url_for('agent.delete_agent_apt', agent_name= current_user.first_name, agent_last_name=current_user.last_name, apartment_public_id=apt.public_id) }}" class="trash-icon"> <button class="btn btn-outline-info"><span style="color: red;" class="icon_trash_alt"></span> Delete Property</button></a>
                         </div>
                        <div class="pi-text">

                            {% if apt.love < 2%}
                            <span >{{apt.love}} love this</span>
                            {% else %}
                            <span >{{apt.love}} loves this</span>
                            {% endif %}

                               {% if apt.price_label == 'full sale' %}
                                   <div class="pt-price">$ {{apt.price}}</div>
                                    {% else %}
                                    <div class="pt-price">$ {{apt.price}}<span>/{{apt.price_label}}</span></div>
                                    {% endif %}
                            <h5><a href="{{ url_for('main.property_details', public_id=apt.public_id) }}"><span style="text-transform: capitalize;">{{apt.property_type[0]}}</span>{{apt.property_type[1:]}} in {{apt.neighbourhood}}</a></h5>
                            <p><span class="icon_pin_alt"></span> {{apt.location}}, {{apt.city}}, {{apt.country}} {{apt.postal_code}}</p>
                            <ul>
                                <li><i class="fa fa-object-group"></i> {{apt.area_size}}</li>
                                <li><i class="fa fa-bathtub"></i> {{apt.no_of_bathrooms}}</li>
                                <li><i class="fa fa-bed"></i> {{apt.no_of_bedrooms}}</li>
                                <li><i class="fa fa-automobile"></i> {{apt.no_of_garages}}</li>
                            </ul>

                        </div>
                    </div>

                </div>
 {%endfor%}

{% if apartment.has_prev %}
         <div class="col-lg-12">
                    <div class="loadmore-btn">
        <a class="btn btn-outline-info" href="{{ url_for('agent.profile', agent_name=agent.first_name, agent_last_name=agent.last_name, page=apartment.prev_num) }}"> Newer </a>{% else %}

            </div>
        </div>
                {% endif %}
{% if apartment.has_next %}
         <div class="col-lg-12">
                    <div class="loadmore-btn">
        <a class="btn btn-outline-info" href="{{ url_for('agent.profile', agent_name=agent.first_name, agent_last_name=agent.last_name, page=apartment.next_num) }}"> Older </a>{% else %}

            </div>
        </div>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- Property Section End -->

{% endblock content%}

base/templates/property.html
{%extends 'layout.html'%}
{% block content%}

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Wrapper Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <span class="icon_close"></span>
        </div>
        <div class="logo">
            <a href="./index.html">

                 <img alt="" src="{{ url_for('static', filename='img/logo.png') }}">

            </a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="om-widget">

               <a class="hw-btn"  href="{{ url_for('main.property_submit') }}">Submit property</a>
        </div>
        <div class="om-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-youtube-play"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
    </div>
    <!-- Offcanvas Menu Wrapper End -->

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="hs-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2">
                        <div class="logo">
                            <a  href="{{ url_for('main.home') }}"> <img alt="" src="{{ url_for('static', filename='img/logo.png') }}"></a>
                        </div>
                    </div>
                    <div class="col-lg-10">
                        <div class="ht-widget">

                              <a class="hw-btn"  href="{{ url_for('main.property_submit') }}">Submit property</a>
                        </div>
                    </div>
                </div>
                <div class="canvas-open">
                    <span class="icon_menu"></span>
                </div>
            </div>
        </div>
        <div class="hs-nav">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <nav class="nav-menu">
                            {% if current_user.is_authenticated%}

                                <h6>{{current_user.first_name}} {{current_user.last_name}}</h6>
                            {% endif %}
                            <ul>
                                <li><a  href="{{ url_for('main.home') }}">Home</a></li>
                                <li class="active"><a href="#">Properties</a>
                                    <ul class="dropdown">
                           <li><a  href="{{ url_for('main.property_list') }}">Property Grid</a></li>

                                              <li><a  href="{{ url_for('main.property_comparison') }}">Property Comperison</a></li>
                                        <li><a  href="{{ url_for('main.property_submit') }}">Property Submit</a></li>
                                    </ul>
                                </li>
                                <li><a  href="{{ url_for('agent.agents') }}">Owners/Agents</a></li>
                                {% if not current_user.is_authenticated%}
                                <li><a  href="{{ url_for('agent.register') }}">Register as an Owner/Agent</a></li>
                                 <li><a  href="{{ url_for('agent.login') }}">Login <i class="fa fa-user"></i></a></li>

                                {%endif%}
                                <li><a href="./blog.html">Blog</a></li>
                                <li><a href="./contact.html">Contact</a></li>
                                 {% if current_user.is_authenticated%}
 <li><a  href="{{ url_for('agent.logout') }}">Logout</a></li>
                            {% endif %}
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-3">
                        <div class="hn-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest-p"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section spad set-bg" data-setbg="{{  url_for('static', filename= 'img/breadcrumb-bg.jpg') }}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h4>Property Grid</h4>
                        <div class="bt-option">
                            <a  href="{{ url_for('main.home') }}"><i class="fa fa-home"></i> Home</a>
                            <span>All Properties </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Property Section Begin -->
    <section class="property-section spad">
        <div class="container">
            <div class="row">
                 <div class="col-lg-6">
                    <div class="agent-search-form">
                        <form action="#">
                            <input type="text" id="livebox" placeholder="Find property by name, city, neighborhood, location, property type, property status, no of rooms, no of bathrooms, no of garages, postal code ">
                                  </form>
                         <span id="datalist" ></span>
                        <script src="{{ url_for('static', filename='ajax.js') }}"></script>
<script src="{{ url_for('static', filename='property_search.js') }}">

</script>
                    </div>
                </div>


                <div class="col-lg-12">
                    <div class="section-title">
                        <h4>PROPERTY Grid</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for apt in apartment.items%}
                <div class="col-lg-4 col-md-6">
                    <div class="property-item">
                        <div class="pi-pic set-bg" data-setbg=" {{  url_for('static', filename= 'Apartment_pics/' + apt.image_file) }}
">
                            <div class="label">{{apt.property_status}}</div>
                        </div>
                        <div class="pi-text">
                            <a href="#" class="heart-icon"><span class="icon_heart_alt"></span></a>
                            {% if apt.price_label == 'full sale' %}
                                    <div class="pt-price">${{apt.price}}</div>
                                    {% else %}
                                   <div class="pt-price">${{apt.price}}<span>/{{apt.price_label}}</span></div>
                                    {% endif %}
                            <h5><a href="{{ url_for('main.property_details', public_id=apt.public_id) }}">Home in {{apt.neighbourhood}}</a></h5>
                            <p><span class="icon_pin_alt"></span> {{apt.location}}, {{apt.city}}, {{apt.country}}, {{apt.postal_code}}</p>
                            <ul>
                                <li><i class="fa fa-object-group"></i> {{apt.area_size}}</li>
                                <li><i class="fa fa-bathtub"></i>{{apt.no_of_bathrooms}}</li>
                                <li><i class="fa fa-bed"></i> {{apt.no_of_bedrooms}}</li>
                                <li><i class="fa fa-automobile"></i> {{apt.no_of_garages}}</li>
                            </ul>
                            <div class="pi-agent">
                                <div class="pa-item">
                                    <div class="pa-info">

                                          <img alt="" src="   {{  url_for('static', filename= 'Apartment_pics/' + apt.broker.agent_image_file) }}">
                                        <h6><a  href="{{ url_for('agent.profile', agent_name=apt.broker.first_name, agent_last_name=apt.broker.last_name) }}">{{apt.broker.first_name}} {{apt.broker.last_name}}</a></h6>
                                    </div>
                                    <div class="pa-text">
                                        {{apt.broker.phone_no}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
{%endfor%}



{% if apartment.has_prev %}
         <div class="col-lg-12">
                    <div class="loadmore-btn">
        <a class="btn btn-outline-info" href="{{ url_for('main.property_list', page=apartment.prev_num) }}"> Newer </a>{% else %}

            </div>
        </div>
                {% endif %}
{% if apartment.has_next %}
         <div class="col-lg-12">
                    <div class="loadmore-btn">
        <a class="btn btn-outline-info" href="{{ url_for('main.property_list', page=apartment.next_num) }}"> Older </a>{% else %}

            </div>
        </div>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- Property Section End -->

      {% endblock content%}